#!/bin/sh
set -e

help()
{
    echo "Usage: ${0} [-t TERMINAL_TYPE]"
    return 0
}

setup_termux()
{
    if test ! "${PREFIX}" = "/data/data/com.termux/files/usr"
    then
        echo "error: you are not using Android/Termux"
        return 1
    fi

    if test ! -d "/data/data/com.termux/files/usr"
    then
        echo "error: termux is not installed"
        return 1
    fi

    termux-change-repo || return 1

    apt install -y x11-repo && \
        apt full-upgrade -y && \
        apt install -y zsh tigervnc vim git xfce4 kitty thunar leafpad netsurf proot-distro iproute2 make nala

    for f in config/etc/profile.d/*.sh
    do
        install -Dm 644 ${f} "${PREFIX}/etc/profile.d/$(basename $f)"
    done

    sudo usermod -s "$(command -v zsh)" "$(whoami)"

    return $?
}

setup_kitty()
{
    if test ! -d "${HOME}/.config/kitty"
    then
        cp -rv --no-preserve=all "config/kitty" "${HOME}/.config"
    fi

    "${SHELL}" -c "./omz install"

    return $?
}

setup_alacritty()
{
    if test ! -d "${HOME}/.config/alacritty"
    then
        cp -rv --no-preserve=all "config/alacritty" "${HOME}/.config"
    fi

    "${SHELL}" "./omz install"

    return $?
}

while getopts 't:' arg
do
    case "${arg}" in
        't') TERMINAL_TYPE="$OPTARG";;
        '?') echo "error: ${arg}: invalid argument"; help;;
    esac
done

if test -z "${TERMINAL_TYPE}"
then
    help
else
    case "${TERMINAL_TYPE}" in
        "termux")       setup_termux;;
        "kitty")        setup_kitty;;
        "alacritty")    setup_alacritty;;
        *)              echo "error: ${TERMINAL_TYPE}: unknown type of terminal";;
    esac
fi
