#!/bin/sh
set -e

install_zsh()
{
    for p in curl zsh git
    do
        if test ! -x $(command -v $p)
        then
            echo "Error: $p: no such file was found"
	    exit 1
        fi
    done

    if test ! -d "$HOME/.oh-my-zsh"
    then
        curl -fsSL "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh" | $SHELL
    else
        echo "Oh My Zsh is already installed"
        read -p "Do you want to reinstall it? [Y/N]: " reinstallOmz
        case $reinstallOmz in
            [Yy]*)
                find $HOME/.oh-my-zsh -exec rm -rfv {} \; && \
                find $HOME/.zshrc -exec rm -v {} \; && \
                    curl -fsSL "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh" | $SHELL
            ;;
            *) break;;
        esac
    fi

    if test ! -d "$HOME/.oh-my-zsh/custom/themes/powerlevel10k"
    then
        zsh -c "source $HOME/.zshrc && \
                git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
                    ${ZSH_CUSTOM:-${HOME}/.oh-my-zsh/custom}/themes/powerlevel10k && \
                omz theme set powerlevel10k/powerlevel10k && \
		chsh -s /bin/zsh $(whoami)"
    fi

    return $?
}

setup_termux()
{
    install_zsh || return 1

    test "$PREFIX" != "/data/data/com.termux/files/usr" && \
        echo ":: ERROR: you are not using Android/Termux" && \
            exit 1

    test ! -d "/data/data/com.termux/files/usr" && \
        echo ":: ERROR: termux is not installed" && \
        exit 1

    termux-change-repo || return 1

    apt install -y x11-repo

    apt full-upgrade -y && \
        apt install -y zsh tigervnc vim git xfce4 kitty thunar \
                        leafpad netsurf proot-distro iproute2 make nala
    find config/etc/profile.d/*.sh -type f -exec install -Dm 644 {} "$PREFIX/etc/profile.d/" \;

    chsh -s zsh

    return $?
}

setup_kitty()
{
    install_zsh || return 1

    for f in curl kitty zsh
    do
	    if test ! -x "$(command -v $f)"
        then
            echo "Please install $f and try again" && exit 1
        fi
    done

    test ! -d "${HOME}/.config/kitty" && mkdir -v "${HOME}/.config/kitty"

    test ! -f "${HOME}/.config/kitty/kitty.conf" && \
        cp -v "config/kitty/kitty.conf" "${HOME}/.config/kitty/kitty.conf"

    for f in MesloLGS%20NF%20Regular.ttf \
             MesloLGS%20NF%20Bold.ttf \
             MesloLGS%20NF%20Italic.ttf \
             MesloLGS%20NF%20Bold%20Italic.ttf
    do
        wget -nc -P $HOME/.fonts --https-only \
             https://github.com/romkatv/powerlevel10k-media/raw/master/$f
    done

    if test ! -d "${HOME}/.oh-my-zsh"
    then
        curl -fsSL "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh" | $SHELL
    elif test ! -d "${HOME}/.oh-my-zsh/custom/themes/powerlevel10k"
    then
        zsh -c "source ${HOME}/.zshrc && \
                git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
                    ${ZSH_CUSTOM:-${HOME}/.oh-my-zsh/custom}/themes/powerlevel10k && \
                omz theme set powerlevel10k/powerlevel10k && \
                chsh -s /bin/zsh `whoami`"
    fi

    test $? -eq 0 && echo "success" || echo "failure"

    return $?
}

setup_xterm()
{
    install_zsh || return 1

    if test ! -x "$(command -v xterm)"
    then
        echo "Please install XTerm and try again" && exit 1
    elif test ! -f "${HOME}/.Xresources"
    then
        cp -v ".config/xterm-settings" "${HOME}/.Xresources"
    fi

    xrdb -merge "${HOME}/.Xresources"

    test $? -eq 0 && echo "success" || echo "failure"

    return $?
}

while getopts 't:' arg
do
    case $arg in
        t) TERMINAL_TYPE=$OPTARG;;
        ?) echo "Usage: ${0} [-t TERMINAL_TYPE]"; exit $?;;
    esac
done

if test -z $TERMINAL_TYPE
then
    echo "Usage: ${0} [-t TERMINAL_TYPE]"
    exit 1
fi

case $TERMINAL_TYPE in
    termux) setup_termux;;
    kitty) setup_kitty;;
    xterm) setup_xterm;;
    *) echo "Error: $TERMINAL_TYPE: unknown type of terminal";;
esac

